# Generated by Django 5.2.5 on 2025-08-10 10:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=1000)),
                ('body', models.TextField()),
                ('portal_name', models.CharField(max_length=100)),
                ('scraped_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('article', 'Article'), ('video', 'Video')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result_count', models.IntegerField(default=0)),
            ],
        ),
    ]
